export const assets = {
  wordmark: "/assets/wordmark.png",
  wordmarkGapCrema: "/assets/wordmark-gap-crema.png",
  wordmarkC: "/assets/wordmark-c.png",
  diamond: "/assets/logo-diamond.png",
  diamondInvert: "/assets/logo-diamond-invert.png",
  pairStudio: "/assets/pair-studio.jpg",
  hero: "/assets/hero.jpg",
  streetMockup: "/assets/street-mockup.jpg",
  wanted: "/assets/wanted.jpg",
  doypackWhite: "/assets/doypack-white.jpg",
  lifestyleSillon: "/assets/lifestyle-sillon.jpg",
  lifestyleCrew: "/assets/lifestyle-crew.jpg",
  lifestyleCalle: "/assets/lifestyle-calle.jpg",
  lifestyleRitual: "/assets/lifestyle-ritual.jpg",
  qr: "/assets/qr-sockets.png",
  campaignFilm: "/assets/BASTA_CC_AE1.mp4",
} as const;
